version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - VITE_API_URL=$VITE_API_URL
        - VITE_API_KEY=$VITE_API_KEY
        - VITE_UPLOAD_DIR=$VITE_UPLOAD_DIR
        - VITE_LICENCE_REDIRECT_URI=$VITE_LICENCE_REDIRECT_URI
        - VITE_PWA_MODE=$VITE_PWA_MODE
    ports:
      - $PORT:$PORT
    environment:
      - PORT=$PORT
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - TOKEN_SECRET=$TOKEN_SECRET
      - CLIENT_URL=$CLIENT_URL
      - UPLOAD_DIR=$UPLOAD_DIR
      - SIB_API_KEY=$SIB_API_KEY
      - BPFMGR_API_KEY=$BPFMGR_API_KEY
      - STATIC_URL=$STATIC_URL
      - API_PREFIX=$API_PREFIX
      - NODE_ENV=production