# Builder of the client
FROM node:14 AS builder
WORKDIR /client
COPY ./client/package*.json ./
RUN npm install
COPY ./client ./

# Get and define env variables
ARG VITE_API_URL
ENV VITE_API_URL ${VITE_API_URL}
ARG VITE_API_KEY
ENV VITE_API_KEY ${VITE_API_KEY}
ARG VITE_UPLOAD_DIR
ENV VITE_UPLOAD_DIR ${VITE_UPLOAD_DIR}
ARG VITE_LICENCE_REDIRECT_URI
ENV VITE_LICENCE_REDIRECT_URI ${VITE_LICENCE_REDIRECT_URI}
ARG VITE_PWA_MODE
ENV VITE_PWA_MODE ${VITE_PWA_MODE}

RUN npm run build

# Final container
FROM node:14 AS final
WORKDIR /app
COPY ./api/package*.json ./
RUN npm install
COPY ./api ./
RUN bash -c 'rm ./public/* && mkdir ./public/uploads && mkdir ./public/uploads/bpfs && mkdir ./public/uploads/profils}'
COPY --from=builder client/dist ./public
COPY ./client/img ./public/img

ARG PORT
ENV PORT ${PORT}
ARG DB_USER
ENV DB_USER ${DB_USER}
ARG DB_HOST
ENV DB_HOST ${DB_HOST}
ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}
ARG DB_NAME
ENV DB_NAME ${DB_NAME}
ARG TOKEN_SECRET
ENV TOKEN_SECRET ${TOKEN_SECRET}
ARG CLIENT_URL
ENV CLIENT_URL ${CLIENT_URL}
ARG UPLOAD_DIR
ENV UPLOAD_DIR ${UPLOAD_DIR}
ARG SIB_API_KEY
ENV SIB_API_KEY ${SIB_API_KEY}
ARG BPFMGR_API_KEY
ENV BPFMGR_API_KEY ${BPFMGR_API_KEY}
ARG STATIC_URL
ENV STATIC_URL ${STATIC_URL}
ARG API_PREFIX
ENV API_PREFIX ${API_PREFIX}
ENV NODE_ENV production

EXPOSE ${PORT}

CMD npm run start
