openapi: 3.1.0
info:
  title: BpfMgr API
  version: 1.0.0
  contact:
    name: Damien STÉPHAN
    email: damienstephan07@gmail.com
  description: Api of BpfMgr
paths:
  /users/all:
    get:
      summary: Get all users
      description: ''
      parameters: []
      operationId: ''
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema: {}
  '/users/:id':
    get:
      summary: Get one user by id
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            enum: []
          description: ID of the user
      operationId: ''
      responses:
        default:
          description: Default response
      tags:
        - users
security: []
servers:
  - url: 'localhost:3000'
    description: Local server
    variables: {}
components:
  links: {}
  callbacks: {}
  schemas: {}
tags:
  - name: users