name: Push Container to Heroku

on:
  push:
    branches:
      - heroku

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: akhileshns/heroku-deploy@v3.12.12
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        PORT: ${{secrets.PORT}}
        DB_HOST: ${{secrets.DB_HOST}}
        DB_USER: ${{secrets.DB_USER}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_NAME: ${{secrets.DB_NAME}}
        TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}
        CLIENT_URL: ${{secrets.CLIENT_URL}}
        UPLOAD_DIR: ${{secrets.UPLOAD_DIR}}
        SIB_API_KEY: ${{secrets.SIB_API_KEY}}
        BPFMGR_API_KEY: ${{secrets.BPFMGR_API_KEY}}
        STATIC_URL: ${{secrets.STATIC_URL}}
        API_PREFIX: ${{secrets.API_PREFIX}}
        VITE_API_URL: ${{secrets.VITE_API_URL}}
        VITE_API_KEY: ${{secrets.VITE_API_KEY}}
        VITE_UPLOAD_DIR: ${{secrets.VITE_UPLOAD_DIR}}
        VITE_PWA_MODE: ${{secrets.VITE_PWA_MODE}}
        VITE_LICENCE_REDIRECT_URI: ${{secrets.VITE_LICENCE_REDIRECT_URI}}
      
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP}}
        usedocker: true
        docker_build_args: |
          PORT
          DB_HOST
          DB_USER
          DB_PASSWORD
          DB_NAME
          TOKEN_SECRET
          CLIENT_URL
          UPLOAD_DIR
          SIB_API_KEY
          BPFMGR_API_KEY
          STATIC_URL
          API_PREFIX
          VITE_API_URL
          VITE_API_KEY
          VITE_UPLOAD_DIR
          VITE_PWA_MODE
          VITE_LICENCE_REDIRECT_URI
